name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
      echo "${{secret.DOCKERPW}}" |docker login -u "exched" --pasword-stdin 
      docker image build -t exched/airlinemanager4bot
      docker push  exched/airlinemanager4bot
